spring:
  application:
    name: smart-campus

  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USER}
    password: ${NEON_DB_PASS}

  sql:
    init:
      mode: always
      platform: postgresql

smartcampus:
  auth:
    initial-admin-email: ${INITIAL_ADMIN_EMAIL:admin@example.com}

server:
  port: 8080
